//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class columns
    {
        public int id { get; set; }
        public string column_name { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> disabled { get; set; }
        public Nullable<int> foreign_id { get; set; }
        public Nullable<int> locked { get; set; }
        public Nullable<System.DateTime> open_until { get; set; }
        public Nullable<int> cart_id { get; set; }
    }
}
