//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lines
    {
        public int id { get; set; }
        public string line_name { get; set; }
        public Nullable<int> row_id { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public Nullable<decimal> center_cm { get; set; }
    }
}
