//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shitaEntities : DbContext
    {
        public shitaEntities()
            : base("name=shitaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<columns> columns { get; set; }
        public virtual DbSet<locations> locations { get; set; }
        public virtual DbSet<product_locations> product_locations { get; set; }
        public virtual DbSet<rows> rows { get; set; }
        public virtual DbSet<scale_log> scale_log { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<lines> lines { get; set; }
        public virtual DbSet<carts> carts { get; set; }
        public virtual DbSet<product_price> product_price { get; set; }
        public virtual DbSet<product_transactions> product_transactions { get; set; }
    }
}
