//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_locations
    {
        public int id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> column_id { get; set; }
        public Nullable<int> row_id { get; set; }
        public Nullable<int> line_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> product_max_quantity { get; set; }
    }
}
