//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rows
    {
        public int id { get; set; }
        public Nullable<int> column_id { get; set; }
        public string row_name { get; set; }
        public Nullable<int> foreign_id { get; set; }
        public Nullable<int> lines { get; set; }
        public Nullable<System.DateTime> last_product_taken { get; set; }
        public Nullable<decimal> width_cm { get; set; }
    }
}
