//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class scale_log
    {
        public int id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> row_foreign_id { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> totalRight { get; set; }
        public Nullable<decimal> totalLeft { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> is_product_taken { get; set; }
    }
}
